// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: statistics.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCategoryStatistics = `-- name: GetCategoryStatistics :many
SELECT 
    c.id,
    c.name,
    COUNT(t.id) as ticket_count
FROM categories c
LEFT JOIN subcategories sc ON sc.category_id = c.id
LEFT JOIN tickets t ON t.subcategory_id = sc.id 
    AND t.is_deleted = false 
    AND t.is_hidden = false
GROUP BY c.id, c.name
ORDER BY ticket_count DESC, c.name
`

type GetCategoryStatisticsRow struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	TicketCount int64  `json:"ticket_count"`
}

func (q *Queries) GetCategoryStatistics(ctx context.Context) ([]GetCategoryStatisticsRow, error) {
	rows, err := q.db.Query(ctx, getCategoryStatistics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategoryStatisticsRow{}
	for rows.Next() {
		var i GetCategoryStatisticsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.TicketCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatisticsSummary = `-- name: GetStatisticsSummary :one
SELECT
    COUNT(*) FILTER (WHERE is_deleted = false AND is_hidden = false) AS total,

    COUNT(*) FILTER (
        WHERE status = 'closed'
        AND is_deleted = false
        AND is_hidden = false
    ) AS resolved,

    COUNT(*) FILTER (
        WHERE status = 'open'
        AND is_deleted = false
        AND is_hidden = false
    ) AS in_progress,

    COUNT(DISTINCT department_id) FILTER (
        WHERE department_id IS NOT NULL
        AND is_deleted = false
        AND is_hidden = false
    ) AS active_executors
FROM tickets
`

type GetStatisticsSummaryRow struct {
	Total           int64 `json:"total"`
	Resolved        int64 `json:"resolved"`
	InProgress      int64 `json:"in_progress"`
	ActiveExecutors int64 `json:"active_executors"`
}

func (q *Queries) GetStatisticsSummary(ctx context.Context) (GetStatisticsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getStatisticsSummary)
	var i GetStatisticsSummaryRow
	err := row.Scan(
		&i.Total,
		&i.Resolved,
		&i.InProgress,
		&i.ActiveExecutors,
	)
	return i, err
}

const getTicketDynamics = `-- name: GetTicketDynamics :many
SELECT
    DATE(created_at) as date,
    COUNT(*) FILTER (WHERE action = 'created') as received,
    COUNT(*) FILTER (WHERE action = 'status_changed' 
        AND new_value::jsonb->>'status' = 'closed') as resolved
FROM ticket_history
WHERE 
    created_at >= $1
    AND created_at <= $2
    AND action IN ('created', 'status_changed')
GROUP BY DATE(created_at)
ORDER BY date ASC
`

type GetTicketDynamicsParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

type GetTicketDynamicsRow struct {
	Date     pgtype.Date `json:"date"`
	Received int64       `json:"received"`
	Resolved int64       `json:"resolved"`
}

func (q *Queries) GetTicketDynamics(ctx context.Context, arg GetTicketDynamicsParams) ([]GetTicketDynamicsRow, error) {
	rows, err := q.db.Query(ctx, getTicketDynamics, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTicketDynamicsRow{}
	for rows.Next() {
		var i GetTicketDynamicsRow
		if err := rows.Scan(&i.Date, &i.Received, &i.Resolved); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketDynamicsByWeek = `-- name: GetTicketDynamicsByWeek :many
SELECT
    DATE_TRUNC('week', created_at)::DATE as week_start,
    COUNT(*) FILTER (WHERE action = 'created') as received,
    COUNT(*) FILTER (WHERE action = 'status_changed' 
        AND new_value::jsonb->>'status' = 'closed') as resolved
FROM ticket_history
WHERE 
    created_at >= $1
    AND created_at <= $2
    AND action IN ('created', 'status_changed')
GROUP BY DATE_TRUNC('week', created_at)
ORDER BY week_start ASC
`

type GetTicketDynamicsByWeekParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

type GetTicketDynamicsByWeekRow struct {
	WeekStart pgtype.Date `json:"week_start"`
	Received  int64       `json:"received"`
	Resolved  int64       `json:"resolved"`
}

func (q *Queries) GetTicketDynamicsByWeek(ctx context.Context, arg GetTicketDynamicsByWeekParams) ([]GetTicketDynamicsByWeekRow, error) {
	rows, err := q.db.Query(ctx, getTicketDynamicsByWeek, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTicketDynamicsByWeekRow{}
	for rows.Next() {
		var i GetTicketDynamicsByWeekRow
		if err := rows.Scan(&i.WeekStart, &i.Received, &i.Resolved); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
