// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE 
    ($1::user_role IS NULL OR role = $1::user_role)
    AND ($2::user_status IS NULL OR status = $2::user_status)
    AND ($3::TEXT IS NULL OR email ILIKE '%' || $3::TEXT || '%')
`

type CountUsersParams struct {
	Role   NullUserRole   `json:"role"`
	Status NullUserStatus `json:"status"`
	Email  *string        `json:"email"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Role, arg.Status, arg.Email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    email,
    role,
    status,
    department_id,
    first_name,
    last_name,
    middle_name
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, email, role, status, department_id, first_name, last_name, middle_name, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID  `json:"id"`
	Email        string     `json:"email"`
	Role         UserRole   `json:"role"`
	Status       UserStatus `json:"status"`
	DepartmentID *int32     `json:"department_id"`
	FirstName    *string    `json:"first_name"`
	LastName     *string    `json:"last_name"`
	MiddleName   *string    `json:"middle_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Role,
		arg.Status,
		arg.DepartmentID,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.DepartmentID,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE id = $1
RETURNING id, email, role, status, department_id, first_name, last_name, middle_name, created_at, updated_at
`

type DeleteUserParams struct {
	ID uuid.UUID `json:"id"`
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) (User, error) {
	row := q.db.QueryRow(ctx, deleteUser, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.DepartmentID,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, role, status, department_id, first_name, last_name, middle_name, created_at, updated_at FROM users
WHERE id = $1 AND status != 'blocked'
`

type GetUserParams struct {
	ID uuid.UUID `json:"id"`
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getUser, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.DepartmentID,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT 
    u.id, u.email, u.role, u.status, u.department_id, u.first_name, u.last_name, u.middle_name, u.created_at, u.updated_at,
    d.name as department_name
FROM users u
LEFT JOIN departments d ON u.department_id = d.id
WHERE 
    ($3::user_role IS NULL OR u.role = $3::user_role)
    AND ($4::user_status IS NULL OR u.status = $4::user_status)
    AND ($5::TEXT IS NULL OR u.email ILIKE '%' || $5::TEXT || '%')
ORDER BY u.created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32          `json:"limit"`
	Offset int32          `json:"offset"`
	Role   NullUserRole   `json:"role"`
	Status NullUserStatus `json:"status"`
	Email  *string        `json:"email"`
}

type ListUsersRow struct {
	ID             uuid.UUID  `json:"id"`
	Email          string     `json:"email"`
	Role           UserRole   `json:"role"`
	Status         UserStatus `json:"status"`
	DepartmentID   *int32     `json:"department_id"`
	FirstName      *string    `json:"first_name"`
	LastName       *string    `json:"last_name"`
	MiddleName     *string    `json:"middle_name"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	DepartmentName *string    `json:"department_name"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Limit,
		arg.Offset,
		arg.Role,
		arg.Status,
		arg.Email,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.DepartmentID,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    role = COALESCE($2::user_role, role),
    status = COALESCE($3::user_status, status),
    department_id = COALESCE($4::INT, department_id),
    first_name = COALESCE($5::VARCHAR, first_name),
    last_name = COALESCE($6::VARCHAR, last_name),
    middle_name = COALESCE($7::VARCHAR, middle_name),
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, role, status, department_id, first_name, last_name, middle_name, created_at, updated_at
`

type UpdateUserParams struct {
	ID           uuid.UUID      `json:"id"`
	Role         NullUserRole   `json:"role"`
	Status       NullUserStatus `json:"status"`
	DepartmentID *int32         `json:"department_id"`
	FirstName    *string        `json:"first_name"`
	LastName     *string        `json:"last_name"`
	MiddleName   *string        `json:"middle_name"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Role,
		arg.Status,
		arg.DepartmentID,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.DepartmentID,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
